#pragma once

union SDL_Event;

namespace Core
{

typedef enum 
{
    SDL_EVENTCATEGORY_QUIT = 0x100,
    SDL_EVENTCATEGORY_WINDOW = 0x200,
    SDL_EVENTCATEGORY_KEYBOARD = 0x300,
    SDL_EVENTCATEGORY_MOUSE = 0x400,
    SDL_EVENTCATEGORY_JOYSTICK = 0x600,
    SDL_EVENTCATEGORY_GAMECONTROLLER = 0x650,
    SDL_EVENTCATEGORY_TOUCH = 0x700,
    SDL_EVENTCATEGORY_GESTURE = 0x800,
    SDL_EVENTCATEGORY_CLIPBOARD = 0x900,
    SDL_EVENTCATEGORY_DRAGDROP = 0x1000,
    SDL_EVENTCATEGORY_AUDIOHOTPLUG = 0x1100,
    SDL_EVENTCATEGORY_RENDER = 0x2000,
    SDL_EVENTCATEGORY_USER = 0x8000,
} SDL_EventCategory;

struct SDL2Util
{
    static bool IsEventCategory(SDL_Event* a_event, SDL_EventCategory a_category);
};

} // namespace Core
