#pragma once

#include "Core/Minimal.h"

#include <stdlib.h>
#include <stdint.h>

#define WindowHandle void *
#define USER_MESSAGE_ID 0x0400

#ifndef MAX_PATH
#define MAX_PATH 256
#endif
#define UOMSG_SET_SERVER_NAME USER_MESSAGE_ID + 660
#define UOMSG_SET_PLAYER_NAME USER_MESSAGE_ID + 661
#define UOMSG_UPDATE_PLAYER_XYZ USER_MESSAGE_ID + 662
#define UOMSG_UPDATE_PLAYER_DIR USER_MESSAGE_ID + 663
#define UOMSG_RECV USER_MESSAGE_ID + 664
#define UOMSG_SEND USER_MESSAGE_ID + 665
#define UOMSG_IP_SEND USER_MESSAGE_ID + 666
#define UOMSG_PATHFINDING USER_MESSAGE_ID + 667
#define UOMSG_WALK USER_MESSAGE_ID + 668
#define UOMSG_MENU_RESPONSE USER_MESSAGE_ID + 669
#define UOMSG_STATUS_REQUEST USER_MESSAGE_ID + 670
#define UOMSG_SELECTED_TILE USER_MESSAGE_ID + 671
#define UOMSG_END_MACRO_PLAYING USER_MESSAGE_ID + 672
#define UOMSG_UPDATE_REMOVE_POS USER_MESSAGE_ID + 673

#define UOMSG_WIN_CLOSE USER_MESSAGE_ID + 1454
#define UOMSG_WIN_SHOW USER_MESSAGE_ID + 1455
#define UOMSG_WIN_PAINT USER_MESSAGE_ID + 1456
#define UOMSG_WIN_ACTIVATE USER_MESSAGE_ID + 1457
#define UOMSG_WIN_SETTEXT USER_MESSAGE_ID + 1458

#define UOMSG_INPUT_KEYDOWN USER_MESSAGE_ID + 1754
#define UOMSG_INPUT_KEYUP USER_MESSAGE_ID + 1755
#define UOMSG_INPUT_MOUSEWHEEL USER_MESSAGE_ID + 1756
#define UOMSG_INPUT_MBUTTONDOWN USER_MESSAGE_ID + 1757
#define UOMSG_INPUT_XBUTTONDOWN USER_MESSAGE_ID + 1758
#define UOMSG_INPUT_CHAR USER_MESSAGE_ID + 1759

#pragma pack(push, 1)

#if defined(_SDL_H) || defined(SDL_h_)
#define USING_SDL_STRUCTS
#endif

#pragma pack(pop)
